# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a157e6a5d491c8fd74e3df1c217e884c7d23709dad88e280367efbee3f082f010e1ceec3889d0e8dbb4478642faf3ed18254f227b8c13dbf49d55a186d0af390

test:
  secret_key_base: d7c9a6b08c0df361de1673e70ca97e979fa53a5b1ba1d124796b92cbb6f534a2f34cb30eef51b4720a69f24b4e0e510eb1d08f20d767cfdcc8c0a9d94df6a9b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
